### ISSUE TITLE
First release

### ISSUE THREAD

**Issue by p-j-smith** [openep/openep-py#58]
There is no release of openep on PyPI.

Tasks to do before first release:

- [x] Switch from TriMesh/Pyvista to PyVista only (#54)
- [x] Make sure documentation builds and is complete (#56 #57)
- [x] Host documentation on read the docs (#55)
- [x] Use pytest instead of unittest (#60)
